name: quiz
description: HKU Adolescent Language Test
publish_to: 'none'
version: 2.0.2

environment:
  sdk: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  random_color: ^1.0.5
  json_annotation: ^3.0.0
  http: ^0.12.2
  intl: ^0.16.1
  flutter_sound: ^6.4.8+2
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  flutter_archive: ^1.0.3

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/A/
    - assets/audios/B/
    - assets/audios/C/
    - assets/audios/D/
    - assets/audios/E/
    - assets/audios/F/1/
    - assets/audios/F/2/
    - assets/audios/instructions/
    - assets/data.json
