name: quiz
description: HKU Adolescent Language Test
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  collection: ^1.14.13
  random_color: ^1.0.5
  json_annotation: ^3.0.0
  http: ^0.12.2
  intl: ^0.16.1
  flutter_sound: ^6.4.8+2
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  stop_watch_timer: ^0.7.0
  flutter_archive: ^1.0.3

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/data.json
