name: quiz
description: HKU Adolescent Language Test
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  assets_audio_player: ^2.0.0
  collection: ^1.14.13
  random_color: ^1.0.5
  json_annotation: ^3.0.0
  http: ^0.12.2
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/data.json
